name: PR Build & Test

on:
  workflow_dispatch:

jobs:
  check:
    runs-on: windows-2022

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Update toolchain
        run: rustup update --no-self-update stable && rustup default stable-x86_64-pc-windows-msvc

      - name: Add toolchain target
        run: rustup target add x86_64-pc-windows-msvc

      - name: Install fmt
        run: rustup component add rustfmt

      - name: Install clippy
        run: rustup component add clippy

      - name: Fix environment
        uses: ./.github/actions/fix-environment

      - name: Clean
        run:  cargo clean

      - name: Run fmt
        run: cargo fmt --all -- --check

      # Test will build the code, then also test it.
      - name: build
        run: cargo build --release

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: Test
          path: ./target/release
